test_color_name_to_hex (__main__.TestExercice) ... ok
test_compute_mse (__main__.TestExercice) ... FAIL
test_create_list (__main__.TestExercice) ... ok
test_list_to_dict (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_compute_mse (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_compute_mse
    'Erreur dans le calcul des MSE'
AssertionError: {} != {'LR': 220.6, 'DNN': 14.0, 'RF': 1681.8}
- {}
+ {'DNN': 14.0, 'LR': 220.6, 'RF': 1681.8} : Erreur dans le calcul des MSE

======================================================================
FAIL: test_list_to_dict (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 25, in test_list_to_dict
    'Mauvaise reponse'
AssertionError: Lists differ: [{0: 'a', 1: 'b', 2: 'z', 3: 'patate'}, {0:[33 chars]re'}] != [{'a': 0, 'b': 1, 'z': 2, 'patate': 3}, {'a[33 chars]: 3}]

First differing element 0:
{0: 'a', 1: 'b', 2: 'z', 3: 'patate'}
{'a': 0, 'b': 1, 'z': 2, 'patate': 3}

- [{0: 'a', 1: 'b', 2: 'z', 3: 'patate'},
-  {0: 'a', 1: '2', 2: 'hello', 3: 'tigre'}]
+ [{'a': 0, 'b': 1, 'patate': 3, 'z': 2},
+  {'2': 1, 'a': 0, 'hello': 2, 'tigre': 3}] : Mauvaise reponse

----------------------------------------------------------------------
Ran 4 tests in 0.003s

FAILED (failures=2)
